### ISSUE TITLE
New Issue?

### ISSUE THREAD

**Issue by SlookHD** [DevLeoko/AdvancedBan#297] opened 2019-11-26 16:32 UTC
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.5
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
1.8.8, 1.12.2, 1.14.4

_Please provide the EXACT steps required to reproduce the problem..._
1.
[latest.log](https://github.com/DevLeoko/AdvancedBan/files/3892872/latest.log)

2.
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

_Add any additional information below._

**Comment by A248** [comment] 2019-12-14 14:19
Duplicate of #203 

Also, please use pastebin instead of uploading your latest.log. It is a hassle to download everyone's latest.log.

**Closed** 2019-12-14 14:35 UTC
Labels: Rejected, Support
