### ISSUE TITLE
[ERROR] Error occurred while enabling AdvancedGUI v2.2.1 

### ISSUE THREAD

**Issue by TimGraham777** [DevLeoko/AdvancedBan#562] opened 2022-04-21 17:32 UTC
_What version of AdvancedBan (`/AdvancedBan`) are you using? 2.2.1
 
Running a Bungeecord server on paper-api-1.18.1-R0.1-SNAPSHOT.jar
 
Errors shows up on startup and Advancedban motion images is not running.

https://pastebin.com/W5GmsY13

Error: 
[20.04 14:20:24] [Server] [INFO] [AdvancedGUI] [STDOUT] Loading default fonts...
[20.04 14:20:24] [Server] [ERROR] Error occurred while enabling AdvancedGUI v2.2.1 (Is it up to date?)
[20.04 14:20:24] [Server] java.lang.UnsatisfiedLinkError/usr/lib/jvm/jdk-17.0.1/lib/libfontmanager.so: libfreetype.so.6: cannot open shared object file: No such file or directory

**Comment by DevLeoko** [comment] 2022-04-21 18:32
In most cases, the cause for this error is the running instance not being able to write to the Java temp directory (java.io.tmpdir).

You could also try deleting the AdvancedGUI/fonts folder and restarting the server, though this probably won't fix the issue.

**Comment by TimGraham777** [comment] 2022-04-21 20:14
I tried deleting the fonts folder but it didn't change. Still getting the error. https://pastebin.com/Cm0dmrUN

**Comment by DevLeoko** [comment] 2022-04-21 20:16
Yes, in most cases, the cause for this error is the running instance not being able to write to the Java temp directory (java.io.tmpdir).

**Comment by TimGraham777** [comment] 2022-04-21 20:19
Would this be something we need to contact our server hosting service about. Is it a Java problem on their server?

**Comment by DevLeoko** [comment] 2022-04-21 20:19
Probably yes

**Comment by TimGraham777** [comment] 2022-04-21 20:20
Thank you! Sorry to have to bother you.

**Closed** 2022-05-02 05:59 UTC
