### ISSUE TITLE
Punishment softlock and DB error until restart

### ISSUE THREAD

**Issue by therealdgrew** [DevLeoko/AdvancedBan#394] opened 2020-08-09 16:37 UTC
I am running the latest version of AdvancedBan (2.2.1) on PaperSpigot MC 1.8.8.

Steps to replicate:
1. Mute or ban someone with the reason in a different language (e.g. Russian - e.g. тест)
2. See the error in chat, attempt unban
3. Unable to unban until server restart, displays player as banned however it reads that player is not banned

Log error:
```
[18:29:03] An unexpected error has occurred executing an Statement in the database
Please check the plugins/AdvancedBan/logs/latest.log file and report this error in: https://github.com/DevLeoko/AdvancedBan/issues
[18:29:03] Query: 
INSERT INTO `Punishments` (`name`, `uuid`, `reason`, `operator`, `punishmentType`, `start`, `end`, `calculation`) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
[18:29:03] java.sql.SQLException: Incorrect string value: '\xD1\x82\xD0\xB5\xD1\x81...' for column 'reason' at row 1
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
    at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
    at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1362)
    at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
    at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
    at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:122)
    at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:107)
    at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:92)
    at me.leoko.advancedban.utils.Punishment.create(Punishment.java:117)
    at me.leoko.advancedban.utils.Punishment.create(Punishment.java:46)
    at me.leoko.advancedban.utils.commands.PunishmentProcessor.accept(PunishmentProcessor.java:72)
    at me.leoko.advancedban.utils.commands.PunishmentProcessor.accept(PunishmentProcessor.java:18)
    at me.leoko.advancedban.utils.Command.execute(Command.java:552)
    at me.leoko.advancedban.manager.CommandManager.lambda$onCommand$0(CommandManager.java:46)
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
[18:29:03] !! Not able to update ID of punishment! Please restart the server to resolve this issue!
[18:29:03] !! Failed at: Punishment{id=-1, name='test', uuid='test', reason='тест', operator='CONSOLE', start=1596990543723, end=1596990843717, calculation='', type=TEMP_MUTE}
```

Screenshots from console: 
![image](https://user-images.githubusercontent.com/59583069/89737178-ad333880-da77-11ea-92ba-0f18b9717d18.png)

**Comment by DevLeoko** [comment] 2020-08-09 18:25
Duplicate of #377

**Closed by DevLeoko** 2020-08-09 18:25 UTC
