### ISSUE TITLE
AsyncPlayerPreLoginEvent error

### ISSUE THREAD

**Issue by A-Valk** [DevLeoko/AdvancedBan#249] opened 2018-09-17 11:05 UTC
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 > [13:03:40 INFO]: -===== AdvancedBan v2 =====-
> [13:03:40 INFO]: Dev • Leoko
> [13:03:40 INFO]: Status • Stable
> [13:03:40 INFO]: Version • 2.1.5-RELEASE
> [13:03:40 INFO]: License • Public
> [13:03:40 INFO]: Storage • MySQL (external)
> [13:03:40 INFO]: Server • Spigot/Bukkit
> [13:03:40 INFO]: UUID-Mode • INTERN
> [13:03:40 INFO]: Prefix • AdvancedBan »
 
_What kind of server do you have (`Bungeecord/single server`)?_
 single spigot
 
_What server version (/version) are you using?_
CraftBukkit version git-Spigot-6b015b4-a222e4a (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

_Please provide the EXACT steps required to reproduce the problem..._
This error occurs sometimes when a player logs in

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/T8FJggCm 

_Add any additional information below._

**Comment by 0xC1A551C** [comment] 2018-09-17 20:59
I have this exact same issue on the same setup.

**Comment by Sandtato** [comment] 2018-10-14 01:01
Can confirm on latest Paper 1.13.1.

**Comment by DevLeoko** [comment] 2018-10-15 07:15
Please check if the latest build fixed your issue: http://v.skamps.eu:8080/job/AdvancedBanV2/49/

**Comment by A-Valk** [comment] 2018-10-16 07:00
`> [08:59:00 WARN]: [AdvancedBan]
§c---------------------------------------------------------------
§cAn error has ocurred loading the punishments from the database.
§c---------------------------------------------------------------`

it is now replaced by this, I dont know if that was the intention?

**Comment by DevLeoko** [comment] 2018-10-17 18:03
Okay, I'll check that out asap, thanks for the report.
You can expect an answer within 3days ;)

**Comment by A-Valk** [comment] 2018-10-18 13:52
latest build (#49) also does not stop banned players from entering the server by the way

**Comment by zenandreas** [comment] 2018-10-26 06:54
Same issue here

**Comment by 0xC1A551C** [comment] 2018-11-06 03:44
Dead plugin?

**Comment by A248** [comment] 2019-12-14 14:15
Duplicate of #203

**Closed** 2019-12-14 14:35 UTC
Labels: Bug, Rejected
