### ISSUE TITLE
Error MySQL

### ISSUE THREAD

**Issue by LeoCrish** [DevLeoko/AdvancedBan#280] opened 2019-05-14 16:59 UTC
Version • 2.1.5-RELEASE

BungeeCord & spigot
 
Spigot 1.12.2

_Please provide the EXACT steps required to reproduce the problem..._
1. Connect the plugin to a MySQL database
2. Ban a player
3. You will get an error

https://pastebin.com/rQPUneGF

**Comment by realhopedev** [comment] 2019-08-30 07:26
### Sorry for the Late Reply!

There's currently an issue with offline-servers and mysql, and might be fixed later on.

If your Server is not cracked, reply to this Message.

**Comment by A248** [comment] 2019-12-14 18:07
Duplicate of #231 .

**Closed** 2019-12-14 18:08 UTC
