### ISSUE TITLE
mySQL Query issue

### ISSUE THREAD

**Issue by lrmtheboss** [DevLeoko/AdvancedBan#274] opened 2019-03-07 01:12 UTC
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.5-RELEASE
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
git:BungeeCord-Bootstrap:1.13-SNAPSHOT:0dd538f:1396 by md_5
and now (4-10-19) git:BungeeCord-Bootstrap:1.13-SNAPSHOT:771f173:1401 by md_5

_Please provide the EXACT steps required to reproduce the problem..._
1.have a player try to log into the server 50% of it happening
2.
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/7Q6k1Dky

_Add any additional information below._
it only happens on the bungeecord, i have the plugin running all servers so that if someone could bypass it on bungeecord it on the server should stop them.
also, have found that it happens more often after the player has just started mc and tried to join the server otherwise, there is a lower chance of it happing
when it happens the player that is trying to log in will just time out and they will have to retry to log in and it normally works at that point
add me on discord at lrmtheboss#7134 and i can show you more of this problem

**Comment by AeSix** [comment] 2019-05-01 11:36
I've been having some similar issues with BungeeCord over the last couple of months worth of builds.  Maybe try using Waterfall? It's a fork of BC, with some improvements.  It's helped me, no failed connection attempts except with extremely poor network conditions on the user's side.

**Comment by lrmtheboss** [comment] 2019-05-01 11:40
Waterfall doesn’t support everything thing I need or I would

**Comment by AeSix** [comment] 2019-05-01 18:42
I don't know of anything that BungeeCord has that Waterfall does not.  Waterfall incorporates the entirety of bungeecord into it's code.  Waterfall only adds to, and changes very very little. I've run a bunch of niche Bungee plugins that work perfectly fine on Waterfall, I can't imagine anything major would break.

**Comment by A248** [comment] 2019-12-14 14:21
Duplicate of #203

**Closed** 2019-12-14 14:36 UTC
Labels: Rejected, Support
