### ISSUE TITLE
Error MySQL

### ISSUE THREAD

**Issue by LeoCrish** [DevLeoko/AdvancedBan#281] opened 2019-05-14 17:04 UTC
Version • 2.1.5-RELEASE

BungeeCord & spigot
 
Spigot 1.12.2

1. Connect the plugin to a MySQL database
2. Ban a player
3. You will get an error

https://pastebin.com/rQPUneGF

MySQL.yml - https://pastebin.com/yrJWyDcq

Config.yml - https://pastebin.com/LDJ3hRPg

**Comment by Elikill58** [comment] 2019-08-12 18:49
I have exactly the same problem

**Comment by A248** [comment] 2019-12-14 13:39
Duplicate of #280

**Closed** 2019-12-14 13:59 UTC
Labels: Rejected, Support
