### ISSUE TITLE
error when player joins

### ISSUE THREAD

**Issue by A-Valk** [DevLeoko/AdvancedBan#237] opened 2018-07-26 16:18 UTC
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.5
 
_What kind of server do you have (`Bungeecord/single server`)?_
 single
 
_What server version (/version) are you using?_
1.13

_Please provide the EXACT steps required to reproduce the problem..._
it's just an error that showed up in the console when the player joined. 

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/EM9Dk22t

_Add any additional information below._
possibly just an error because 1.13 is not supported?

**Comment by DevLeoko** [comment] 2018-08-08 08:38
Sorry for the late response ^^
Please check if you still get this error with our latest build: http://v.skamps.eu/jenkins/job/AdvancedBanV2/46/

**Comment by A248** [comment] 2019-12-14 13:54
Duplicate of #203

**Closed** 2019-12-14 13:57 UTC
Labels: Rejected, Support
