### ISSUE TITLE
Problem (MySQL)

### ISSUE THREAD

**Issue by xJust1n** [DevLeoko/AdvancedBan#242] opened 2018-08-10 17:49 UTC
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.5-Release
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Spigot Server
 
_What server version (/version) are you using?_
CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) 
(Implementing API version 1.8.8-R0.1-SNAPSHOT)

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/2xABNir4

**Comment by DevLeoko** [comment] 2018-08-25 09:49
This issue should be resolved by our latest build: http://v.skamps.eu/jenkins/job/AdvancedBanV2/47/ 
(Sorry for the late response)

**Comment by Draagoo25** [comment] 2018-10-27 12:57
The link throws an error 404.

Btw, I got the same problems with my bungeecord server.

**Comment by A248** [comment] 2019-12-14 13:55
Duplicate of #203

**Closed** 2019-12-14 13:57 UTC
Labels: Rejected, Support
