### ISSUE TITLE
Advancedban Error in console when ever a player joins

### ISSUE THREAD

**Issue by Arrowheads844** [DevLeoko/AdvancedBan#293] opened 2019-10-01 05:30 UTC
_What version of AdvancedBan (`/AdvancedBan`) are you using_
**2.1.5-RELEASE**
 
 
_What kind of server do you have (`Bungeecord/single server`)?_
**Spigot**
 
 
_What server version (/version) are you using?_
**1.12.2 - Latest (--rev 1.12.2)**

_Please provide the EXACT steps required to reproduce the problem..._
1. Player Logs into server
2. Error occurs
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._ 
**https://pastebin.com/3Hurtk5b**
**https://pastebin.com/1NMHqMae**

_Add any additional information below._
**I am running the plugin on my spigot server (1.12.2 Latest - the server is in offline mode because it is connected to a bungee cord proxy, Version: 1.14.4) and when a player joins [This Error](https://pastebin.com/3Hurtk5b) occurs. The error happens with all players (Default, New, Old, OP, Staff, etc..) It says it may be an issue with the database, so I better give you the info: It is a local MySQL (version: 8.0.13) database with the user "plugin" having full access to everything and the directory "plugins".  I have java 8 (version: JDK-191) installed on the server. The plugin is up-to-date with all the latest required plugins for the server to run cross-compatibility (Via Version, Via Rewind, and Via Backwards)**

**Comment by A248** [comment] 2019-12-14 13:49
Duplicate of #203

**Closed** 2019-12-14 13:58 UTC
Labels: Rejected, Support
