### ISSUE TITLE
Show outstanding warnings

### ISSUE THREAD

**Issue by jQuery0** [DevLeoko/AdvancedBan#100] opened 2017-07-05 19:59 UTC
Hi,

Make it so that when you temp warned someone for example 1 week, it shows a message on player join saying

Caution: you have outstanding warnings {reason}

**Comment by DevLeoko** [comment] 2017-07-06 20:04
I will consider adding this

**Comment by DevLeoko** [comment] 2020-03-09 14:51
duplicate of #227

**Closed by DevLeoko** 2020-03-09 14:51 UTC
Labels: Feature-Request
