### ISSUE TITLE
Error Could not pass event AsyncPlayerPreLoginEvent to AdvancedBan v 2.1.5-RELEASE 

### ISSUE THREAD

**Issue by Mrok71** [DevLeoko/AdvancedBan#299] opened 2019-12-17 18:53 UTC
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.5
 
_What kind of server do you have (`Bungeecord/single server`)?_
 single server paperclip
 
_What server version (/version) are you using?_
Paper git-Paper-236 (MC:1.14.4)

_Please provide the EXACT steps required to reproduce the problem..._
1. n/a (Error in consol)

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/pk9Wdgec

_Add any additional information below._

**Comment by A248** [comment] 2019-12-18 00:39
Duplicate of #203

**Closed by A248** 2019-12-18 00:39 UTC
