### ISSUE TITLE
Error API

### ISSUE THREAD

**Issue by cluedo10** [DevLeoko/AdvancedBan#273] opened 2019-03-02 17:08 UTC
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 AdvancedBan-2.1.5-RELEASE
 
_What kind of server do you have (`Bungeecord/single server`)?_
 BungeeCord
 
_What server version (/version) are you using?_
1.8.8

_Please provide the EXACT steps required to reproduce the problem..._
1.I enter
2.banned
3.and the error occurs

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/Aiiy0EHY

_Add any additional information below._
I made a plugin and integrate the api of this plugin and when the ban occurs that error.

**Comment by realhopedev** [comment] 2019-08-22 09:14
If this is still a issue, could you please post your Code?

**Comment by A248** [comment] 2019-12-14 17:51
Duplicate of #280 .

@realhopedev it does not seem to be related to API usage - the plugin logs indicate the punishment was valid. Rather, it seems to be the same bug as in #280 . **This issue is a misnomer**.

**Closed** 2019-12-14 18:04 UTC
