### ISSUE TITLE
/history not showing expired punishments

### ISSUE THREAD

**Issue by tWizT3ddreaMr** [DevLeoko/AdvancedBan#383] opened 2020-07-29 04:05 UTC
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.2.1[hotfix]
 
_What kind of server do you have (`Bungeecord/single server`)?_
 single
 
_What server version (/version) are you using?_
git-Paper-377 (MC: 1.15.2)

_Please provide the EXACT steps required to reproduce the problem..._
1. Have a punishement
2. Let it expire(timewise)
3. do /history

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_
https://pastebin.com/4FWvDdMH

_Add any additional information below._
Looked into it, but it is driving me mad. 
Tracking up and down the issue I think it is coming from the [getPunishments](https://github.com/DevLeoko/AdvancedBan/blob/b4bbb6a68ddca46616ec8dacae1218477a4a18b2/src/main/java/me/leoko/advancedban/manager/PunishmentManager.java#L118) thinking current in history it true

**Comment by DevLeoko** [comment] 2020-07-29 18:05
Thanks for the report. This got fixed in the latest dev build.
The error message has nothing to do with this issue, it is caused by the Paper Version you are using (try updating)

This issue will be closed once the version gets released.

**Closed** 2020-10-25 19:21 UTC
Labels: Bug, Solved
