### ISSUE TITLE
/unban console error

### ISSUE THREAD

**Issue by BCBAdrian** [DevLeoko/AdvancedBan#379] opened 2020-07-19 07:54 UTC
Stable 2.2.0
 
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single
 
_What server version (/version) are you using?_
git-paper-99 (MC 1.16.1)

_Please provide the EXACT steps required to reproduce the problem..._
1. /ban someone
2. /unban someone
3. See Console

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_
[https://pastebin.com/XrRj6HGs](Link)

**Comment by DevLeoko** [comment] 2020-07-19 17:48
I can't really tell what is going wrong here. It has something to do with synchronizing the AdvancedBan Bans to the Vanilla BanSystem. Maybe try to use a different PaperBuild as this issue seems to be caused by paper.

Also, if the issue persists please check the banned-players.json file and report how it is affected by /ban and /unban

**Comment by BCBAdrian** [comment] 2020-07-20 11:43
I updated the kernel, there is no problem yet. By the way, my actions had no effect on the banned-players.json file, it is empty all the time (I don't know if it's good or bad :crying_cat_face:  ). In general, the problem has not yet been observed, but it is better to keep this topic open for now, suddenly the problem will appear again. (Paper has released two updates this day :smile_cat:  )

**Comment by DevLeoko** [comment] 2020-07-21 06:20
For the unwarn command you use the punishment id. One way to find out a punishment ID is with the "/warns NAME" command.

If the bug does not persist please do close this issue and just reopen it if it ever reoccurs.

**Closed** 2020-07-25 11:27 UTC
Labels: Bug
