### ISSUE TITLE
Statement in the database error

### ISSUE THREAD

**Issue by Querko7** [DevLeoko/AdvancedBan#203] opened 2018-05-02 07:01 UTC
_What version of AdvancedBan (`/AdvancedBan`) are you using?_

 §8[]=====[§7Enabling AdvancedBan§8]=====[]
§8| §cInformation:
§8|   §cName: §7AdvancedBan
§8|   §cDeveloper: §7Leoko
§8|   §cVersion: §72.1.5-SNAPSHOT
§8|   §cStorage: §7MySQL (external)
§8| §cSupport:
§8|   §cSkype: §7Leoko33
§8|   §cMail: §7Leoko4433@gmail.com
§8|   §cGithub: §7https://github.com/DevLeoko/AdvancedBan/issues
§8|   §cDiscord: §7https://discord.gg/ycDG6rS
§8| §cUpdate:
§8|   §7There is a new version available! [2.1.4]
§8[]================================[]§f
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_

??9This server is running BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:fde2c3f:1310 by md_5

_Please povide the EXACT steps required to reproduce the problem..._
1.
2.
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

https://pastebin.com/QQNkj8MF

_Add any additional information below._

Latest.log:
https://pastebin.com/k8qvn0XR

**Comment by DevLeoko** [comment] 2018-05-03 17:28
seems to be the same bug as #198. Thanks for the report

**Comment by RainOfPain125** [comment] 2018-05-04 00:58
I'll subskroob to this report incase I can help someway.

**Comment by itaquito** [comment] 2018-05-19 18:03
Any updates? My console is full of this error. :p

**Comment by LuaTenshi** [comment] 2018-07-16 17:17
This error is still around...

```
>AdvancedBan
[17:10:33 INFO]: -===== AdvancedBan v2 =====-
[17:10:33 INFO]:   Dev ? Leoko
[17:10:33 INFO]:   Status ? Stable
[17:10:33 INFO]:   Version ? 2.1.5-RELEASE
[17:10:33 INFO]:   License ? Public
[17:10:33 INFO]:   Storage ? MySQL (external)
[17:10:33 INFO]:   Server ? Spigot/Bukkit
[17:10:33 INFO]:   UUID-Mode ? INTERN
[17:10:33 INFO]:   Prefix ? AdvancedBan ?
[17:10:33 INFO]: -=========================-
>version
[17:11:08 INFO]: This server is running CraftBukkit version git-Spigot-642f6d2-57ab4cf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
```

```
[16:22:39 INFO]: [AdvancedBan] An unexpected error has ocurred executing an Statement in the database
Please check the plugins/AdvancedBan/logs/latest.log file and report thiserror in: https://github.com/DevLeoko/AdvancedBan/issues
[16:22:39 ERROR]: Could not pass event AsyncPlayerPreLoginEvent to AdvancedBan v2.1.5-RELEASE
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.LoginListener$LoginHandler.fireEvents(LoginListener.java:271) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.LoginListener$3.run(LoginListener.java:224) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
Caused by: java.lang.NullPointerException
        at me.leoko.advancedban.manager.PunishmentManager.load(PunishmentManager.java:47) ~[?:?]
        at me.leoko.advancedban.Universal.callConnection(Universal.java:212) ~[?:?]
        at me.leoko.advancedban.bukkit.listener.ConnectionListener.onConnect(ConnectionListener.java:20) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        ... 5 more
```

```
[16:22:39] An unexpected error has ocurred executing an Statement in the database
Please check the plugins/AdvancedBan/logs/latest.log file and report thiserror in: https://github.com/DevLeoko/AdvancedBan/issues
[16:22:39] Query: 
SELECT * FROM `Punishments` WHERE `uuid` = ? OR `uuid` = ?
```

**Comment by A248** [comment] 2019-12-14 13:45
I have the same issue. It doesn't seem to be at all related to online/offline mode. However, I have noticed it only occurs with external storage (MySQL).

**Comment by A248** [comment] 2019-12-14 13:48
#291 , another duplicate of this issue, provides more testimony to suggest this bug is MySQL-specific.

**Comment by A248** [comment] 2019-12-14 14:02
I believe the root cause of this bug is a null UUID value somehow working its way into the plugin data. That would explain both messages:

- ``` SELECT * FROM `Punishments` WHERE `uuid` = ? OR `uuid` = ?` ``` is well-explained by my hypothesis. Apparently some drivers accept a null second parameter for PreparedStatement#setObject(int, Object) according to https://stackoverflow.com/questions/15581370/safety-of-setobject-and-null. In that case, uuid would be null. I presume that #setObject(int, Object) where the Object is null would let the parameter remain `?` meaning null. Therefore, I would conclude that the bug is a null value being set by #setObject(int, Object).

- ``` Could not pass event AsyncPlayerPreLoginEvent to AdvancedBan v2.1.5-RELEASE
org.bukkit.event.EventException: null ``` reflects the same bug, but its corresponding symptom. Here, a null value is retrieved rather than set.

**Comment by A248** [comment] 2019-12-15 20:28
A possible patch would be to check for null values when information is sent to and retrieved from the database. However, that would not fix the root cause of this problem, which is a null uuid.

**Comment by DevLeoko** [comment] 2020-03-09 14:29
Should be solved with the newest version: https://www.spigotmc.org/resources/advancedban.8695/update?update=321631

Thanks to @A248

**Closed by DevLeoko** 2020-03-09 14:29 UTC
Labels: Bug
