### ISSUE TITLE
MySQL statement error

### ISSUE THREAD

**Issue by Chappy202** [DevLeoko/AdvancedBan#268] opened 2018-12-28 11:59 UTC
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.5
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single server
 
_What server version (/version) are you using?_
git-Spigot-db6de12-18fbb24 (MC: 1.8.8) API version 1.8.8-R0.1-SNAPSHOT

_Please provide the EXACT steps required to reproduce the problem..._
1. Enable MySQL connection to external database that is not hosted on the same machine as the server.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/incLYWEq

_Add any additional information below._

**Comment by Resi23** [comment] 2019-01-03 14:34
Same Problem 

What version of AdvancedBan (/AdvancedBan) are you using?
2.1.5-RELEASE

What kind of server do you have (Bungeecord/single server)?
Bungeecord (Waterfall)

What server version (/version) are you using?
Waterfall-Bootstrap:1.13-SNAPSHOT:3d6cccb:244

Please provide the EXACT steps required to reproduce the problem...

Enable MySQL connection to database that is hosted on the same machine as the server (localhost).

Any error/log post it through pastebin.com and link it here.
Waterfall Log: https://pastebin.com/b9Y9cXfz
AdvancedBan Log: https://pastebin.com/fgwxizaB

**Comment by lukaskabc** [comment] 2019-01-23 20:34
Yes, I have same problem too
(Spigot 1.13.2)

**Comment by HgeX** [comment] 2019-02-01 19:57
Same problem here...
Version: 2.1.5-Release
Spigot 1.13.2

**Comment by AeSix** [comment] 2019-05-01 12:00
Ahhhh finally!  @DevLeoko  - it appears this issue is not strictly related to external SQL servers, or Bungee/waterfall vs Spigot/Paper. 

I am using MariaDB local to my Waterfall/Bungee server (I've tested with both, same issue, not a server specific issue) 

> bungee
```
This server is running Waterfall version git:Waterfall-Bootstrap:1.14-SNAPSHOT:0ba8f21:281 by md_5
```
> advancedban
```
[07:43:19 INFO]: -===== AdvancedBan v2 =====-
[07:43:19 INFO]:   Dev • Leoko
[07:43:19 INFO]:   Status • Stable
[07:43:19 INFO]:   Version • 2.1.5-RELEASE
[07:43:19 INFO]:   License • Public
[07:43:19 INFO]:   Storage • MySQL (external)
[07:43:19 INFO]:   Server • Bungeecord
[07:43:19 INFO]:   RedisBungee • false
[07:43:19 INFO]:   UUID-Mode • MIXED
[07:43:19 INFO]:   Prefix • Minecats 
```
From console:
```
[07:10:27 INFO]: [AdvancedBan] An unexpected error has ocurred executing an Statement in the database
Please check the plugins/AdvancedBan/logs/latest.log file and report thiserror in: https://github.com/DevLeoko/AdvancedBan/issues
[07:10:27 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@4d411036, id=1171, owner=me.leoko.advancedban.bungee.BungeeMain@3420547, task=me.leoko.advancedban.bungee.listener.ConnectionListenerBungee$$Lambda$330/1613733814@7d96a12d, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException: null
        at me.leoko.advancedban.manager.PunishmentManager.load(PunishmentManager.java:47) ~[?:?]
        at me.leoko.advancedban.Universal.callConnection(Universal.java:212) ~[?:?]
        at me.leoko.advancedban.bungee.listener.ConnectionListenerBungee.lambda$onConnection$0(ConnectionListenerBungee.java:24) ~[?:?]
        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:0ba8f21:281]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

From AdvancedBan lastest.log:
```
[07:10:27] An unexpected error has ocurred executing an Statement in the database
Please check the plugins/AdvancedBan/logs/latest.log file and report thiserror in: https://github.com/DevLeoko/AdvancedBan/issues
[07:10:27] Query:
SELECT * FROM `Punishments` WHERE `uuid` = ? OR `uuid` = ?
```

Additionally:
I tested with a recent version of BungeeCord, as well as the specified version of Waterfall.  The error occurs without provocation, seemingly random - perhaps a scheduled task?  I do not use AdvancedBan on the backend servers.  However, currently I have a mix of Spigot and Paper, 1.12.2 and 1.13.2 servers on the backend. 1.12.2, 1.13.2 and 1.14 clients may connect to all of our servers, we're using ViaVersion 2.0.2-Snapshot to achieve this.  

Source file lines indicated in the error, for your convience:
https://github.com/DevLeoko/AdvancedBan/blob/master/src/main/java/me/leoko/advancedban/manager/PunishmentManager.java#L47
https://github.com/DevLeoko/AdvancedBan/blob/master/src/main/java/me/leoko/advancedban/Universal.java#L212
https://github.com/DevLeoko/AdvancedBan/blob/master/src/main/java/me/leoko/advancedban/bungee/listener/ConnectionListenerBungee.java#L24

Thank you for your time and the otherwise great plugin!

**Comment by A248** [comment] 2019-12-14 14:20
Duplicate of #203

**Closed** 2019-12-14 14:35 UTC
Labels: Rejected, Support
