### ISSUE TITLE
Console error before a player enters

### ISSUE THREAD

**Issue by FASHv10** [DevLeoko/AdvancedBan#291] opened 2019-09-25 19:22 UTC
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
2.1.5-RELEASE
 
 
_What kind of server do you have (`Bungeecord/single server`)?_
Single
 
 
_What server version (/version) are you using?_
Spigot-1.8.8

_Please provide the EXACT steps required to reproduce the problem..._
1. I don't really know why this error happens, it only appears sometimes in the console before a user enters, but this does not always happen, it happens randomly

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/1NMHqMae

_Add any additional information below._
This error began to appear after I put the MYSQL

**Comment by A248** [comment] 2019-12-14 13:48
Duplicate of #203 .

**Closed** 2019-12-14 13:58 UTC
Labels: Rejected, Support
