### ISSUE TITLE
Something with mysql :(

### ISSUE THREAD

**Issue by 6u5t4v** [DevLeoko/AdvancedBan#285] opened 2019-08-09 15:08 UTC
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.5
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single
 
_What server version (/version) are you using?_
spigot 1.8.8-R0.1-SNAPCHAT

_Please provide the EXACT steps required to reproduce the problem..._
1. Log into the server
2. error appears in log

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/LEdfcHag

_Add any additional information below._

**Comment by realhopedev** [comment] 2019-08-30 07:24
### Sorry for the Late Reply!

There's currently an issue with offline-servers and mysql, and might be fixed later on.

If your Server is not cracked, reply to this Message.

**Comment by 6u5t4v** [comment] 2019-08-30 07:59
My server is not cracked, and I am not sure what this message is about ?

**Comment by A248** [comment] 2019-12-14 14:24
Duplicate of #203

**Closed** 2019-12-14 14:37 UTC
Labels: Rejected, Support
