### ISSUE TITLE
Tab completion for nickname

### ISSUE THREAD

**Issue by Twonox** [DevLeoko/AdvancedBan#44] opened 2017-01-27 18:40 UTC
Ab version: latest
Serveur version: latest 1.8.8 (with bungeecord)

When I want to complete a nick, the wrote chars are reset and all online player's name is browsed by tabulation, no completion for target nick.

e.g. I want to ban Twonox:
1. I write /ban Two
2. I use [TAB] to complete the nick
3. TWO is replaced by AAA, then by BBB etc.

**Comment by ZombieHDGaming** [comment] 2017-01-29 04:54
Since someone will eventually ask you this, are you using this on Bukkit/Spigot or BungeeCord, because your server version is a bit confusing.

If you are using Bukkit/Spigot, I will look into this and try to find the issue and make a pull request. If you are on BungeeCord, I will still try and find the issue, but I may not be able to help you as I am not that experienced with BC. I would also check your server settings, and plugins, for anything to do with tab completion, as this may also cause an issue.

**Comment by md678685** [comment] 2017-01-29 08:42
@ZombieHDGaming I assumed he was running AB on the server which was behind BungeeCord. 
In Bukkit and Spigot it is impossible to globally override tab completion for all commands; plugins can only do it per-command and there are no "settings" for it. BungeeCord usually passes tab completion through to the server unless it is disabled, in which case it won't work at all.

Regardless, I can confirm that this is an issue on Paper 1.11.2, which also doesn't alter tab completion behaviour as far as I know.

@Twonox Could you paste a list of plugins you are running?

**Comment by Twonox** [comment] 2017-01-29 12:18
I use Ab with bungee, not in single server.

Plugins: https://hastebin.com/gomaxusawo.nginx

**Comment by md678685** [comment] 2017-01-29 14:48
What Bungee plugins are you running?

**Comment by Twonox** [comment] 2017-01-29 15:01
AdvancedBan, BungeeAuthmeBridge, BungeeMotd, Bungeeperms, CommandDispatcher, SkinRestorer and Socket4MC

**Comment by ZombieHDGaming** [comment] 2017-01-29 17:11
@md678685 Actually, there is an event for tab completion to prevent it, and edit the completions, I am currently testing other commands for custom completions. Also, your bug confirmation is actually null. I just tested AdvancedBan 2.0.6 on the latest Spigot and PaperSpigot, freshly built, and tab complete works fine for players. As for you @Twonox, this is an interesting situation. I have not tested BC AdvancedBan yet, but I will have to test it and see if I get the same result as you do.

So yes. Current Standing: Spigot/PaperSpigot/Bukkit are fine, BungeeCord is still currently unknown. I think this is safe to say, this is a per-server error basis.

**Comment by md678685** [comment] 2017-01-29 19:12
@Twonox https://github.com/DevLeoko/AdvancedBan/blob/99c31889c15d2876813a5d221da9e9d7d66274d7/src/me/leoko/advancedban/bungee/listener/CommandReceiverBungee.java#L25

This is probably intended. Rather than filtering players, it just tab completes using a list of all players. It's not a bug as such, but could probably be improved.

**Comment by ZombieHDGaming** [comment] 2017-01-29 19:57
I made a PR to hopefully make a quick fix for this, and hopefully prevent something like this in the future. If this gets pulled in, it should fix your issue :)

**Comment by dutchy1001** [comment] 2017-01-29 19:58
Can this fix also use tab completion for offline players when in the data base (either data.yml or MySQL)?

**Comment by ZombieHDGaming** [comment] 2017-01-29 20:11
Currently, it does not. My pull was just a rewrite for the original tab complete to add for already typed text completion. Again, as I don't know much about BungeeCord I could not say if I could do this. Although, if other devs wanted to try their hand in this, they most likely could try and modify my PR to add that feature.

**Comment by DevLeoko** [comment] 2017-01-30 13:58
The PR got merged after some imporvements on the code ;) thanks @ZombieHDGaming 

Advanced Tab Completion for offline players, layouts, time types etc. will be added in a future version of advancedban :)

**Closed by DevLeoko** 2017-01-30 13:58 UTC

**Comment by Twonox** [comment] 2017-01-30 16:46
Is there dev build of this update ?

**Comment by DevLeoko** [comment] 2017-01-30 16:51
No sorry, but the code is public so feel free to compile it by your own

**Comment by Twonox** [comment] 2017-01-30 21:50
Erf, I tried compile Ab with Eclipse and its Git perspective but when I try to create the Java project from the ab git files I receive this error: https://hastebin.com/amaciyozuk.pl
I did successfully the clone of the ab repo, idk why there is this error.

**Comment by ZombieHDGaming** [comment] 2017-01-30 22:00
I am currently out, but when I get home, I'll have a Crack at compiling AB.

**Comment by ZombieHDGaming** [comment] 2017-01-30 23:40
I made a new build here:
https://www.mediafire.com/?v94twq8dd66ywil

Sorry the size is a tad bit bigger than Leoko's normal builds, he most likely has a program compress the JAR farther than what I have my Eclipse compiler set to. Also sorry for using MediaFire :P

**Comment by Twonox** [comment] 2017-01-31 16:55
I've tested the tab completion, but it sadly doesn't work :/

**Comment by ZombieHDGaming** [comment] 2017-01-31 17:02
Is it at least tabbing properly? Or is it like it was before?

**Comment by ZombieHDGaming** [comment] 2017-01-31 17:12
Okay, I NOW have the proper build done. This should fix tab completing and any fix that was added in the last few days.

https://www.mediafire.com/?vz35d9canl86e1q

**Comment by Twonox** [comment] 2017-01-31 17:17
Thanks but my antivirus say that is can malicious. Should I trust you ? :o x)

**Comment by ZombieHDGaming** [comment] 2017-01-31 17:30
What virus protection do you use? Also, you can decompile if you would like and look. I do not even know where to start with hacking, so I wouldn't be able to do anything.

But yes, I have done nothing with the source files besides a few clean ups.

**Comment by Twonox** [comment] 2017-01-31 17:45
I use McAfee WebAdvisor

**Comment by ZombieHDGaming** [comment] 2017-01-31 17:47
Word of advice, never use McAfee. I would suggest Norton as a better option. While Norton is a yearly thing, it has better detection than McAfee ever will. Plus McAfee has been known for it's false detections, or no detections at all for hgih risk files.

**Comment by dutchy1001** [comment] 2017-01-31 19:24
Neither anti virus programs I will ever recommend.
As McAfee in know for false detection, Norton slows your pc down (they probably both do). 1 other bad point is that both have to be paid for.
Avast or AVG both have free versions that do just as good, or even better then McAfee or Norton.

**Comment by Twonox** [comment] 2017-01-31 19:32
I use only McAfee for Web protection.
The antivirus that I use for my computer is Windows Defender. I know, the antivirus make the computer more slow, for this reason I deleted McAfee a long time ago.
But also now, I deleted Mcafee Web Advisor for false danger detection. I'm open to your suggestion for only Web protection

**Comment by Twonox** [comment] 2017-01-31 19:33
I tested your update ZombieHDGaming, and I'm happy to say that IT WORKS ! :p thank you again

**Comment by ZombieHDGaming** [comment] 2017-01-31 19:34
For just web protection, that's hard to say. Web protection isn't exactly a very high priority, as your virus software and browser mainly scan for this. If anything, I would say just use your normal system protection for this. Also, you are welcome. Let me know if there is anything else you want tweaked, and I will look into getting it done.

**Comment by Twonox** [comment] 2017-01-31 19:50
Mhmm, I have an other (very little) request, at the moment. It's to add /banip because there is only /ipban which works,

**Comment by ZombieHDGaming** [comment] 2017-01-31 19:54
@Twonox banip is already implemented as an alias. Have you tested this to see if it works? If not, I will most likely have to figure out a fix and push a PR to fix it on here as well.

**Comment by dutchy1001** [comment] 2017-01-31 20:02
You have to add _- banip_ also to the essentials config "**disabled-commands**" section or it will interfere with AdvancedBan.

**Comment by Twonox** [comment] 2017-01-31 20:12
I will test your suggestion dutchy, but I don't understand why ab's /banip can have interference with essentials whereas the other commands works fine.

**Comment by dutchy1001** [comment] 2017-01-31 20:17
This is what I experienced before and adding that to the essentials file fixed it for me. 
I think it used the essentials ipban instead of the Advancedban.

**Comment by dutchy1001** [comment] 2017-01-31 20:21
When using the command _/ipban_ it used the essentials version.
When using the command _/banip_ it used the AdvancedBan version.
For ease you type /ipban faster then the otherway around lol

**Comment by Twonox** [comment] 2017-01-31 20:25
/ipban is handled by Ab, not by essentials

**Comment by dutchy1001** [comment] 2017-01-31 20:28
It could be a leftover setting from when I uses v10.3. It just popped up in my mind when you asked for adding the command. If all works fine without it been added to the essentials config then forget I said some. 
Better to much info then to less 😜

**Comment by Twonox** [comment] 2017-01-31 20:47
I did the test in my test server, and I noticed that the command `/banip` works fine only if Ab isn't in BungeeCord.

**Comment by dutchy1001** [comment] 2017-01-31 20:51
Then when placed in the bungeecord Essentials takes over as this is on the server and not in your bungee.
If you test it with bungee and add the command to the "disabled-commands" it should work fine again.

**Comment by Twonox** [comment] 2017-01-31 21:06
Ok, now i'm not able to test. I give news tomorrow

**Comment by dutchy1001** [comment] 2017-01-31 21:06
no worries

**Comment by Twonox** [comment] 2017-02-01 12:30
I did what you said but it completely disable the command `/banip`

> why ab's /banip can have interference with essentials whereas the other commands works fine.

It seemed evident that is not the cause.

**Comment by dutchy1001** [comment] 2017-02-01 13:28
Indeed the command does not do anything atm, I just tested this too. But to be honest I type /ipban as I'm used to that command and it feels allien to type it the otherway.

**Comment by DevLeoko** [comment] 2017-02-01 14:03
Well, it seems like the aliases are not working in BungeeCord :D I'm normally only coding Spigot/Bukkit Plugins so I did not know about this ^^ I'll fix it in a future version

**Comment by ZombieHDGaming** [comment] 2017-02-01 14:04
@Devleoko aka, I'll most likely make a PR for it....

**Comment by dutchy1001** [comment] 2017-02-11 20:14
Hows the tab completion error coming along? any more news or tests on it??

**Comment by ZombieHDGaming** [comment] 2017-02-11 20:19
The tab completion was confirmed as fixed, unfortunately, the aliases for BungeeCord may be out of reach due to how AdvancedBan is currently setup. As all the commands are not currently a "solid state (hard coded into system)," a full rewrite of the BungeeCord command system may need to happen for aliases to work properly.

**Comment by dutchy1001** [comment] 2017-02-11 20:29
that conformation was only made on your build as far I understand, has there been a PR made for a new version that can be released by Leoko?

**Comment by ZombieHDGaming** [comment] 2017-02-11 20:38
I just looked inside the PR section, and the last PRs were made by myself, nearly 2 weeks ago.

**Comment by dutchy1001** [comment] 2017-02-11 20:45
So it's just waiting for a new release then...
