### ISSUE TITLE
Error in QUERY

### ISSUE THREAD

**Issue by AlexBanPer** [DevLeoko/AdvancedBan#279] opened 2019-05-01 16:34 UTC
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.5-RELEASE
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Its Network, but is installed in every single server (No premium)
 
_What server version (/version) are you using?_
version git-Spigot-f09662d-f40143e (MC: 1.13.2)

_Please provide the EXACT steps required to reproduce the problem..._
1. Load server and wait 20 minutes.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/H4FzZ1Kf

_Add any additional information below._
We try to change the DataBase.

**Comment by realhopedev** [comment] 2019-08-30 07:23
### Sorry for the Late Reply!

There's currently an issue with offline-servers and mysql, and might be fixed later on.

**Comment by A248** [comment] 2019-12-14 14:23
Duplicate of #203 

Also, @realhopedev , this is not offline-server specific. See #203 for my brief explanation.

**Closed** 2019-12-14 14:36 UTC
Labels: Rejected, Support
