### ISSUE TITLE
An unexpected error has occurred executing an Statement in the database

### ISSUE THREAD

**Issue by CrazyLeV** [DevLeoko/AdvancedBan#390] opened 2020-08-07 10:09 UTC
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.2.0
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
CraftBukkit 1.8.8

_Please provide the EXACT steps required to reproduce the problem..._
1. when someone kicks or gets banned, this error pops up
2.
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_
https://pastebin.com/WEsVLxmD

_Add any additional information below._

**Comment by DevLeoko** [comment] 2020-08-07 12:45
Duplicate of #377

**Closed by DevLeoko** 2020-08-07 12:45 UTC
