### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PixelNotFound** [DevLeoko/AdvancedBan#270] opened 2019-01-23 18:38 UTC
> 18:37:48 [INFO] [AdvancedBan] An unexpected error has ocurred executing an Statement in the database
Please check the plugins/AdvancedBan/logs/latest.log file and report thiserror in: https://github.com/DevLeoko/AdvancedBan/issues
> 18:37:48 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@1a1d3c1a, id=24, owner=me.leoko.advancedban.bungee.BungeeMain@b27b210, task=me.leoko.advancedban.bungee.listener.ConnectionListenerBungee$$Lambda$150/1346984347@5e6cb20a, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException
at me.leoko.advancedban.manager.PunishmentManager.load(PunishmentManager.java:47)
at me.leoko.advancedban.Universal.callConnection(Universal.java:212)
at me.leoko.advancedban.bungee.listener.ConnectionListenerBungee.lambda$onConnection$0(ConnectionListenerBungee.java:24)
at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

**Comment by A248** [comment] 2019-12-14 14:20
Duplicate of #203

**Closed** 2019-12-14 14:35 UTC
Labels: Rejected, Support
