### ISSUE TITLE
An unexpected error has ocurred executing an statement in the database

### ISSUE THREAD

**Issue by ChrissTM03** [DevLeoko/AdvancedBan#336] opened 2020-04-28 15:52 UTC
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.5-RELEASE
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord(FLAMECORD)

_What server version (/version) are you using?_
1.12.2 Paper

_Please provide the EXACT steps required to reproduce the problem..._
1.Just running the server it send my that issue

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/VkZs6SrT

_Add any additional information below._

latest.log text here:

[02:44:43] An unexpected error has ocurred executing an Statement in the database
Please check the plugins/AdvancedBan/logs/latest.log file and report thiserror in: https://github.com/DevLeoko/AdvancedBan/issues
[02:44:43] Query: 
SELECT * FROM Punishments WHERE uuid = ? OR uuid = ?
[17:17:07] An unexpected error has ocurred executing an Statement in the database
Please check the plugins/AdvancedBan/logs/latest.log file and report thiserror in: https://github.com/DevLeoko/AdvancedBan/issues
[17:17:07] Query: 
SELECT * FROM Punishments WHERE uuid = ? OR uuid = ?

**Comment by DevLeoko** [comment] 2020-04-28 20:53
Duplicate of #325

**Closed by DevLeoko** 2020-04-28 20:53 UTC
