### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Craftaris** [DevLeoko/AdvancedBan#277] opened 2019-04-23 07:30 UTC
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 The latest one.
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Single servver

_What server version (/version) are you using?_
1.13.2

_Please provide the EXACT steps required to reproduce the problem..._
1. On player join event
2.
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/Eisgt1Kz

_Add any additional information below._

**Comment by AeSix** [comment] 2019-05-01 11:28
@Invaerne94  

first off, "lastest" is NOT a version.  Please either download the newest release or build, notate the actual version (or build number), test.  That number is what is important for Leoko to be able to identify and fix the issue.  Or, you know, issue the "/AdvanceBan" command to get that information from the copy you're currently running. 

Second, though Leoko didn't specify it in the question, when reporting issues, you should always supply the server implementation and server build version.  It makes things easier to debug for the dev so they can make sure they can test with the same code you are using. 

Third, You can use \`\`\` marks to wrap your error in the issue tracker so that you don't have to use a paste site that may (or /will/) remove your paste over time.  This also helps other users, like me, be able to easily search the issue tracker for duplicates of the issue I'm having.  In addition, it helps the dev to stay focused on the task and maybe be able to actually stay interested enough to fix it. 

Following these basic guidelines for reporting issues helps EVERYBODY, including yourself.

**Comment by AeSix** [comment] 2019-05-01 11:30
@Invaerne94 try building a new copy of Spigot with BuildTools.  See if that helps.  If it does fix the issue, please close the ticket.  

If it does NOT resolve the issue, please reply with the information, as much detail as you can, so that the dev actually has info to work with.

**Comment by A248** [comment] 2019-12-14 14:22
Duplicate of #203

**Closed** 2019-12-14 14:37 UTC
Labels: Rejected, Support
