### ISSUE TITLE
Unexpected error executing a Statement in the database

### ISSUE THREAD

**Issue by S0lan** [DevLeoko/AdvancedBan#342] opened 2020-05-04 13:05 UTC
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 
 
_What kind of server do you have (`Bungeecord/single server`)?_
Bungee
 
 
_What server version (/version) are you using?_
#1492 Bungee Build

/version gives: 
git-Spigot-2040c4c-893ad93

_Please provide the EXACT steps required to reproduce the problem..._
1. When logging in after being offline for a while this error comes.
Not really doing anything.
2. When this Error comes, It says "Timed out" in Minecraft. When i try to reconnect again, it works like a charm. Happens once in a while.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/yyvBaMX1

_Add any additional information below._

**Comment by DevLeoko** [comment] 2020-05-05 05:01
Duplicate of #325

**Closed** 2020-05-05 05:01 UTC
