### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by metclocker** [DevLeoko/AdvancedBan#283] opened 2019-07-24 13:10 UTC
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 Latest
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Spigot
 
_What server version (/version) are you using?_
1.14.3

_Please provide the EXACT steps required to reproduce the problem..._
It shows this error messages on console if Player tried to speak when they are in mute condition.

> [12:21:23] [Server thread/ERROR]: Could not pass event AsyncPlayerChatEvent to AdvancedBan v2.1.3-RELEASE
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) [spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
at net.minecraft.server.v1_14_R1.PlayerConnection.chat(PlayerConnection.java:1592) [spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
at org.bukkit.craftbukkit.v1_14_R1.entity.CraftPlayer.chat(CraftPlayer.java:328) [spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
at com.earth2me.essentials.commands.Commandsudo.updatePlayer(Commandsudo.java:49) [EssentialsX-2.17.0.5.jar:?]
at com.earth2me.essentials.commands.EssentialsLoopCommand.loopOnlinePlayers(EssentialsLoopCommand.java:98) [EssentialsX-2.17.0.5.jar:?]
at com.earth2me.essentials.commands.Commandsudo.run(Commandsudo.java:34) [EssentialsX-2.17.0.5.jar:?]
at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:171) [EssentialsX-2.17.0.5.jar:?]
at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:543) [EssentialsX-2.17.0.5.jar:?]
at com.earth2me.essentials.Essentials.onCommand(Essentials.java:458) [EssentialsX-2.17.0.5.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) [spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) [spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:692) [spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:433) [spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:397) [spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:955) [spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:800) [spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IllegalStateException: RevokePunishmentEvent cannot be triggered asynchronously from inside synchronized code.
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) ~[spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
at me.leoko.advancedban.bukkit.BukkitMethods.callRevokePunishmentEvent(BukkitMethods.java:351) ~[?:?]
at me.leoko.advancedban.utils.Punishment.delete(Punishment.java:204) ~[?:?]
at me.leoko.advancedban.manager.PunishmentManager.getPunishments(PunishmentManager.java:93) ~[?:?]
at me.leoko.advancedban.manager.PunishmentManager.getMute(PunishmentManager.java:159) ~[?:?]
at me.leoko.advancedban.bukkit.BukkitMethods.callChat(BukkitMethods.java:224) ~[?:?]
at me.leoko.advancedban.bukkit.listener.ChatListener.onChat(ChatListener.java:15) ~[?:?]
at sun.reflect.GeneratedMethodAccessor432.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
... 20 more

**Comment by A248** [comment] 2019-12-14 14:23
Duplicate of #203

**Closed** 2019-12-14 14:36 UTC
Labels: Rejected, Support
