### ISSUE TITLE
Error with mysql

### ISSUE THREAD

**Issue by Spartan9802** [DevLeoko/AdvancedBan#275] opened 2019-03-21 23:20 UTC
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
AdvancedBan 2.1.5
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
Spigot 1.8.8

_Please provide the EXACT steps required to reproduce the problem..._
1.Spam joins the server with a banned account
2.You can join the server, the error is generated

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://pastebin.com/B3MgmL4c

_Add any additional information below._
It is possible that the error only occurs if you have ping and you spawn to join the server

**Comment by AeSix** [comment] 2019-05-01 11:33
You probably want to update Bungee (or use Waterfall) if you're using the 1.8 era version of Bungeecord.  The newest releases of BC support 1.8-1.13.2 (with some 1.14 support)  

if that helps, please close the ticket.  If it don't, let us know.

**Comment by A248** [comment] 2019-12-14 14:21
Duplicate of #203

**Closed** 2019-12-14 14:36 UTC
Labels: Rejected, Support
