### ISSUE TITLE
An unexpected error has occurred executing an Statement in the database

### ISSUE THREAD

**Issue by itaquito** [DevLeoko/AdvancedBan#332] opened 2020-04-24 13:54 UTC
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 
 2.1.8
_What kind of server do you have (`Bungeecord/single server`)?_
 
 Bungeecord (Waterfall)
_What server version (/version) are you using?_
This server is running Paper version git-Paper-165 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

_Please provide the EXACT steps required to reproduce the problem..._
1. Log in to the server

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

https://pastebin.com/XWxYScK4
_Add any additional information below._
Nop

Thanks!

**Comment by DevLeoko** [comment] 2020-04-24 14:30
Duplicate of #325

**Closed by DevLeoko** 2020-04-24 14:30 UTC
